app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDate.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarFragment.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarMonth.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/testCalendarData.kt
> calendar 데모영상용 로직
데모 영상용 데이터 파일 : testCalendarData.kt 
7월 1일 ~ 8월 4일까지 데이터 만들었습니다
구현 영상 카톡에 올리겠습니당
=> [demo/#123]calendar 데모영상용 로직

app/src/main/java/com/umc/yourweather/presentation/HomeWeatherInputFragment.kt, app/src/main/res/anim/btn_weather_scale.xml
> 날씨 아이콘 클릭 이벤트 기능 구현
[yourweather_weatherbtn.webm](https://github.com/yourweather/yourweather_android/assets/102938120/dfc55b27-8abc-4f62-af90-7b712fc18983)
=> [feat/#138] homeweatherinput / 날씨 아이콘 클릭 이벤트 기능 구현

app/src/main/AndroidManifest.xml
=> [remove/#148] manifest / 삭제된 액티비티 관련 코드 제거

app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDate.kt, app/src/main/java/com/umc/yourweather/util/CalendarUtils.kt
> 오늘 날짜 표시 기능 추가
구현 영상 카톡에 올리겠습니다
=> [feat/#47]캘린더에 오늘 날짜 표시 기능 추가

app/src/main/java/com/umc/yourweather/presentation/CalendarDetailView1.kt, app/src/main/java/com/umc/yourweather/presentation/CalendarDetailView3.kt
>캘린더 상세보기 로직 수정 
지금 노트북이 너무 느린 나머지..영상을 찍으려고 다시 run을 실행하는 중인데 렉이 자꾸 걸려 영상을 바로 올리진 못했지만.. 실행되는 대로 영상 올리겠습니다..!
=> [demo/#156]calendardetailview/캘린더 상세보기 로직 수정 

app/src/main/java/com/umc/yourweather/presentation/calendar/testCalendarData.kt
=> [demo]  8월 4일 100도 수정

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SocialSignCheck.kt, app/src/main/res/layout/activity_social_sign_check.xml, settings.gradle
> 레트로핏 의존성 추가, base url 추가
참고한 블로그 : https://www.pinslog.com/119
import com.umc.yourweather.BuildConfig 해주시고 아래와 같이 사용하시면 됩니다
=> [setting/#163]레트로핏 의존성 추가, base url 추가

app/src/main/res/layout/fragment_my_page.xml
=> [refactor/#174] 마이페이지 / 첫 번째 뷰 디자인 수정

app/src/main/java/com/umc/yourweather/data/entity/BarData.kt, app/src/main/java/com/umc/yourweather/data/entity/ItemUnwritten.kt, app/src/main/java/com/umc/yourweather/data/entity/ItemWritten.kt, app/src/main/java/com/umc/yourweather/presentation/adapter/UnwrittenRVAdapter.kt, app/src/main/java/com/umc/yourweather/presentation/adapter/WrittenRVAdapter.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/UnwrittenDetailListFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloud.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloudWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRain.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRainWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSunWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunder.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunderWeekly.kt
>[setting] : data class 패키지 옮김
=> [setting] : data class 패키지 옮김

app/src/main/java/com/umc/yourweather/presentation/analysis/IconStaticsMonthlyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/IconStaticsWeeklyFragment.kt, app/src/main/res/layout/fragment_icon_statics_monthly.xml, app/src/main/res/layout/fragment_icon_statics_weekly.xml
> 비교분석 뷰 내 달 넘김 기능 구현
https://github.com/yourweather/yourweather_android/assets/83583757/ddf6131a-3faf-4f97-8318-c73091ed86ad
=> [feat/#161] 비교분석 뷰 내 달 넘김 기능 구현

app/src/main/java/com/umc/yourweather/di/RetrofitApi.kt, app/src/main/java/com/umc/yourweather/presentation/sign/GlobalApplication.kt, app/src/main/java/com/umc/yourweather/util/PreferenceUtil.kt
>레트로핏 오프젝트
GlobalAppliacation.kt -> 에디님 프로젝트 파일의 App 입니다(메니페스트에서 android:name=""으로 호출되는 부분-> 어플 실행시 가장 먼저 실행)
util 폴더 내 PreferenceUtil.kt
di 폴더 내 RetrofitApi.kt
=> [feat/#192]레트로핏 오프젝트

app/.gitignore, app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/yourweather/di/App.kt
> .gitnore 수정
> 소셜로그인 초기화코드 App.kt에 추가
=> [refactor]api setting

google-services.json
> 구글 소셜로그인 정보 파일 추가(ignored file)
=> [add] : 구글 소셜로그인 정보 파일 추가(ignored file)

google-services.json
=> [remove]removed cached

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/yourweather/presentation/BottomNavi.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageAlarm.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageFragment.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageMyInfo.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageNicknameChange.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePwChange.kt, app/src/main/res/layout/activity_my_info.xml, app/src/main/res/layout/activity_my_page_alarm.xml, app/src/main/res/layout/activity_my_page_nickname_change.xml, app/src/main/res/layout/activity_my_page_pw_change.xml, app/src/main/res/layout/fragment_my_page.xml
=> [feat/#194] 마이페이지 - 알림설정 뷰 연결

app/src/main/java/com/umc/yourweather/data/service/MemoService.kt, app/src/main/java/com/umc/yourweather/data/service/UserService.kt
> userservice, memoservice 내용 추가
=> [feat/#208] service / user,memo service 항목 구현

app/src/main/java/com/umc/yourweather/data/remote/request/LoginRequset.kt, app/src/main/java/com/umc/yourweather/data/remote/response/TokenResponse.kt, app/src/main/java/com/umc/yourweather/data/service/LoginService.kt
> LoginService 생성
임시 명세서 기반으로 생성했습니다
=> [feat/#207]LoginService 생성

app/src/main/java/com/umc/yourweather/data/remote/request/LoginRequest.kt, app/src/main/java/com/umc/yourweather/data/service/LoginService.kt
> 파일명 오타 수정 LoginRequset.kt->LoginRequest.kt
=> [refactor/ #207] : 파일명 오타 수정 LoginRequset.kt->LoginRequest.kt 

app/src/main/java/com/umc/yourweather/data/service/EmailService.kt, app/src/main/java/com/umc/yourweather/data/service/WeatherService.kt
> email, weather service 항목 구현
=> [feat/#213] service / email, weather service 항목 구현

app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageFragment.kt, app/src/main/res/layout/fragment_my_page.xml
=> [refactor/] mypage_first / 뷰 및 기능 수정

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/yourweather/di/RefreshTokenService.kt, app/src/main/java/com/umc/yourweather/di/RetrofitImpl.kt, app/src/main/java/com/umc/yourweather/di/TokenAuthenticator.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignUp.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt, app/src/main/res/xml/network_security_config.xml
> 회원가입_이메일 api 기능 구현
**재전송의 경우 기능 수정 후 배포가 진행되지 않은 상태 => 인증 횟수 초과 테스트는 배포 후 재진행 예정
기능 구현 관련하여 카톡에 동영상 올렸슴당**
**- 로그캣**
일부러 인증코드 다르게 한 번 입력 해봤어용 !
=> [feat/#225] 회원가입_이메일 / api 기능 구현

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/yourweather/presentation/sign/FindPw.kt, app/src/main/java/com/umc/yourweather/presentation/sign/FindPwEmail.kt, app/src/main/java/com/umc/yourweather/presentation/sign/ResetPw.kt, app/src/main/res/layout/activity_find_pw_email.xml, app/src/main/res/layout/activity_pw_reset.xml, app/src/main/res/values/strings.xml
> [add] 비밀번호 찾기 로직 뷰 구현
디코에 스크린샷 올렸습니다
=> [add/#223]  [add] 비밀번호 찾기 로직 뷰 구현

app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailviewDiaryAdapter.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView1.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView2.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView3.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewEmpty.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify1.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify2.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendardetailviewAlarm.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/HorizontalScrollFragment.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/HorizontalScrollFragment2.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ModifyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ModifyFragment2.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ScrollviewFragment1.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ScrollviewFragment2.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/WritingNowFragment.kt, app/src/main/res/layout/activity_calendardetailview_alarm.xml, app/src/main/res/layout/card_calendar_detailview.xml, app/src/main/res/layout/fragment_horizontal_scroll.xml, app/src/main/res/layout/fragment_horizontal_scroll2.xml, app/src/main/res/layout/fragment_modify.xml, app/src/main/res/layout/fragment_modify2.xml, app/src/main/res/layout/fragment_scrollview1.xml, app/src/main/res/layout/fragment_scrollview2.xml, app/src/main/res/layout/fragment_writing_now.xml, app/src/main/res/values/ids.xml
> 캘린더 상세보기 파일 패키지 이동 
비율코딩 수정 필요 & 알람설정 기능은 아직 구현하지 못한 상황입니다..얼른 구현시키겠습니다..!
=> [setting/#193] 캘린더 상세보기/캘린더 상세보기 파일 패키지 이동 

app/src/main/java/com/umc/yourweather/di/RetrofitImpl.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt, app/src/main/res/layout/fragment_bar_statics_monthly.xml, app/src/main/res/layout/fragment_bar_statics_weekly.xml
> 비교분석뷰 지난 주/달 비교 데이터 텍스트 코드 구조 변경
=> [refactor/#232] 비교분석뷰 지난 주/달 비교 데이터 텍스트 코드 구조 변경

app/src/main/java/com/umc/yourweather/data/service/LoginService.kt, app/src/main/java/com/umc/yourweather/di/RetrofitImpl.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt, app/src/main/res/layout/activity_sign_in.xml
=> [feat/#229] signin api

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdarw3.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw2.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/WithdrawPageFragment.kt, app/src/main/res/drawable/btn_mypage_ok.xml, app/src/main/res/drawable/btn_withdraw1.xml, app/src/main/res/drawable/btn_withdraw2.xml, app/src/main/res/drawable/button_no.xml, app/src/main/res/drawable/button_yes.xml, app/src/main/res/drawable/mypage_line.xml, app/src/main/res/drawable/mypage_record.xml, app/src/main/res/drawable/mypage_record2.xml, app/src/main/res/layout/activity_my_page_withdraw.xml, app/src/main/res/layout/activity_my_page_withdraw2.xml, app/src/main/res/layout/activity_my_page_withdraw3.xml, app/src/main/res/layout/alert_dialog_mypage_withdraw.xml, app/src/main/res/layout/fragment_withdraw_page.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
> [add/#237] 마이페이지 탈퇴진행 뷰 구현 
https://github.com/yourweather/yourweather_android/assets/122203161/1d473ee1-54fa-478f-b8b5-01da5dd19b96
=> [add/ #237] 마이페이지 탈퇴진행 뷰 구현

app/src/main/java/com/umc/yourweather/data/remote/response/TokenResponse.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
=> [refactor/#229] : 로그인 후 홈화면 이동 

app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt, app/src/main/res/layout/fragment_bar_statics_monthly.xml, app/src/main/res/layout/fragment_bar_statics_weekly.xml
> 비교분석 bar 통계 부분 API 붙이기 
해당 파일에서 필요한 api 붙이기 작업이 끝나면 머지 요청 드릴테니 아직은 머지하지 말아주세여!!
=> [feat#249] 비교분석 bar 통계 부분 API 붙이기 

app/src/main/java/com/umc/yourweather/data/service/LoginService.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
=> [feat/#251] 소셜 로그인 api 테스트 완

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify1.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify2.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ModifyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ModifyFragment2.kt, app/src/main/res/layout/activity_calendar_detailview_modify1.xml, app/src/main/res/layout/activity_calendar_detailview_modify2.xml, app/src/main/res/layout/alertdialog_calendar_detailview_modify.xml, app/src/main/res/values/ids.xml
> 캘린더 상세보기 저장 버튼 기능 구현 
키보드 구현을 아직 만족시키지 못했습니다..얼른 수정해볼게요..
https://github.com/yourweather/yourweather_android/assets/122203161/be3413b6-b3c7-4a63-9bc1-31be98128451
=> [add/#254]캘린더 상세보기 / 캘린더 상세보기 저장 버튼 기능 구현 

app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt, app/src/main/res/drawable/ic_certain.xml, app/src/main/res/layout/fragment_bar_statics_monthly.xml, app/src/main/res/layout/fragment_bar_statics_weekly.xml
> 증가, 감소, 동일에 따른 화살표 이미지 변경 기능
증가, 감소, 동일에 따른 화살표 이미지 변경 기능
=> [feat/#252] 증가, 감소, 동일에 따른 화살표 이미지 변경 기능

app/src/main/AndroidManifest.xml
=> [hofix/#] : manifest file수정 #261

app/src/main/java/com/umc/yourweather/data/service/ReportService.kt, app/src/main/java/com/umc/yourweather/data/service/WeatherDataListener.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/IconStaticsMonthlyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/IconStaticsWeeklyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloud.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloudWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRain.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRainWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSunWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunder.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunderWeekly.kt, app/src/main/res/layout/fragment_icon_statics_weekly.xml, app/src/main/res/layout/fragment_written_detail_list_cloud.xml, app/src/main/res/layout/fragment_written_detail_list_rain.xml, app/src/main/res/layout/fragment_written_detail_list_sun.xml, app/src/main/res/layout/fragment_written_detail_list_sun_weekly.xml, app/src/main/res/layout/fragment_written_detail_list_thunder.xml
> detail list api 붙이기 비교분석뷰
https://github.com/yourweather/yourweather_android/assets/83583757/578a7d86-0708-40d5-b079-cdc9f3ec6cf5
=> [feat/#266] detail list api 붙이기 비교분석뷰

app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendardetailviewAlarm.kt, app/src/main/res/layout/activity_calendardetailview_alarm.xml, app/src/main/res/layout/activity_my_page_withdraw2.xml, app/src/main/res/values/styles.xml
=> [fix / #269] 마이페이지, 알람창 오류 수정

app/src/main/java/com/umc/yourweather/data/service/ReportService.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloud.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRain.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunder.kt
=> [refactor/#274] 비교분석 /  status import 오류 수정

app/src/main/res/layout/fragment_written_detail_list_cloud.xml, app/src/main/res/layout/fragment_written_detail_list_cloud_weekly.xml, app/src/main/res/layout/fragment_written_detail_list_rain.xml, app/src/main/res/layout/fragment_written_detail_list_rain_weekly.xml, app/src/main/res/layout/fragment_written_detail_list_sun.xml, app/src/main/res/layout/fragment_written_detail_list_sun_weekly.xml, app/src/main/res/layout/fragment_written_detail_list_thunder.xml, app/src/main/res/layout/fragment_written_detail_list_thunder_weekly.xml
> 각 날씨 디테일 리스트 뷰 구조, 텍스트 사이즈 수정
=> [fix/#276] 각 날씨 디테일 리스트 뷰 구조, 텍스트 사이즈 수정

app/src/main/java/com/umc/yourweather/di/RetrofitImpl.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
=> [feat]retrofit token

app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
=> [feat/#280] 자동로그인 추가

app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
=> [feat#280] : 자동로그인

app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt
=> [hotfix/#286] : 플랫폼 네이밍 오류 수정

app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDate.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarFragment.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarMonth.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarTotalViewFragment.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt
=> [feat/#288]캘린더 디테일뷰로 weatherId 전송

app/src/main/java/com/umc/yourweather/data/service/ReportService.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloudWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRainWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSunWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunderWeekly.kt, app/src/main/res/layout/fragment_written_detail_list_cloud.xml, app/src/main/res/layout/fragment_written_detail_list_cloud_weekly.xml, app/src/main/res/layout/fragment_written_detail_list_rain.xml, app/src/main/res/layout/fragment_written_detail_list_rain_weekly.xml, app/src/main/res/layout/fragment_written_detail_list_sun.xml, app/src/main/res/layout/fragment_written_detail_list_sun_weekly.xml, app/src/main/res/layout/fragment_written_detail_list_thunder.xml, app/src/main/res/layout/fragment_written_detail_list_thunder_weekly.xml
=> [feat/#292] 주 중 특정 날씨 리스트 요청 API 붙이기

app/src/main/java/com/umc/yourweather/di/RetrofitImpl.kt
=> [retactor/#291] : 레트로핏.. 

app/src/main/java/com/umc/yourweather/presentation/sign/Nickname.kt, app/src/main/res/layout/activity_nickname.xml
> 회원가입 기능 수정
회원가입 완료 시 siginin으로 이동 안되는데 일단 코드 붙여서 올립니다!
향후 수정하도록 하겠습니다 !
=> [fix/#289] 회원가입 / 기능 수정

app/src/main/java/com/umc/yourweather/di/UserSharedPreferences.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageLogoutFragment.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePwChange.kt
> [hotfix] : SH 파일 이름 변경으로 인한 이슈 수정
=> [hotfix/#304] : SH 파일 이름 변경으로 인한 이슈 수정

app/build.gradle, app/src/main/java/com/umc/yourweather/data/remote/response/VerifyEmailResponse.kt, app/src/main/java/com/umc/yourweather/data/service/UserService.kt, app/src/main/java/com/umc/yourweather/presentation/sign/FindPw.kt, app/src/main/java/com/umc/yourweather/presentation/sign/FindPwEmail.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt, app/src/main/java/com/umc/yourweather/util/SignUtils.kt, app/src/main/res/layout/activity_find_pw.xml, app/src/main/res/layout/activity_find_pw_email.xml
> 비번 찾기 api
이메일은 배포 전이라 테스트가 불가합니다 일단 애뮬 오류는 안납니다,,
=> [feat/#302]비번 찾기 api

app/src/main/java/com/umc/yourweather/presentation/sign/ResetPw.kt, app/src/main/java/com/umc/yourweather/util/SignUtils.kt
=> [feat/#309]비밀번호 재설정 api

app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePlus.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePlusAlarm.kt, app/src/main/res/layout/activity_my_page_plus.xml, app/src/main/res/layout/activity_my_page_plus_alarm.xml, app/src/main/res/layout/alertdialog_my_page_plus_delete.xml
=> [add/#312] 마이페이지 / 마이페이지 이벤트 기록 설정 뷰 구현 

app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageMyInfo.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdarw3.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw2.kt, app/src/main/java/com/umc/yourweather/util/AlertDialogTwoBtn.kt, app/src/main/res/layout/activity_my_page_withdraw2.xml, app/src/main/res/layout/activity_my_page_withdraw3.xml, app/src/main/res/layout/alertdialog_twobtn.xml, app/src/main/res/values/strings.xml
> 회원탈퇴 뷰 수정, api 붙임
커스텀 토스트(정말 유어웨어 회원을 탈퇴하시겠습니까?) 만들어놨으니 혹시 나중에 비슷한 뷰 추가되거나 하면 이거 쓰시면 될 것 같습니당...
비번 찾을 때 이메일 인증하는건 성공은 하는데 이메일 코드가 안 오네요ㅠ 서버에 물어보겠습니다
회원탈퇴 api는 성공입니다
=> [feat/#313]회원탈퇴 api

app/src/main/java/com/umc/yourweather/data/entity/ItemWritten.kt, app/src/main/java/com/umc/yourweather/data/remote/response/MemoReportResponseDto.kt, app/src/main/java/com/umc/yourweather/data/remote/response/SpecificMemoResponse.kt, app/src/main/java/com/umc/yourweather/data/remote/response/StatisticResponse.kt, app/src/main/java/com/umc/yourweather/presentation/adapter/WrittenRVAdapter.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/AnalysisFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloud.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloudWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRain.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRainWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSunWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunder.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunderWeekly.kt, app/src/main/res/drawable/ic_certain.xml, app/src/main/res/drawable/ic_downarrow.xml, app/src/main/res/drawable/ic_uparrow.xml, app/src/main/res/values/dimes.xml
=> [fix/#306] 비교분석 뷰 API 수정 

app/src/main/java/com/umc/yourweather/presentation/BottomNavi.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarTotalViewFragment.kt, app/src/main/java/com/umc/yourweather/presentation/sign/Nickname.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt, app/src/main/java/com/umc/yourweather/presentation/weatherinput/InitialNoWeatherFragment.kt
=> [Feat/#329]회원가입시 바로 홈화면으로

app/src/main/java/com/umc/yourweather/data/remote/request/ChangePasswordRequest.kt, app/src/main/java/com/umc/yourweather/data/remote/request/ResetPasswordRequest.kt, app/src/main/java/com/umc/yourweather/data/remote/response/ChangePasswordRespond.kt, app/src/main/java/com/umc/yourweather/data/remote/response/ResetPwResponse.kt, app/src/main/java/com/umc/yourweather/data/service/UserService.kt, app/src/main/java/com/umc/yourweather/di/UserSharedPreferences.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPagePwChange.kt, app/src/main/java/com/umc/yourweather/presentation/sign/ResetPw.kt, app/src/main/res/layout/activity_pw_reset.xml
=> [fix/#333] 바뀐 API에 따라 비밀번호 변경 수정

app/src/main/java/com/umc/yourweather/presentation/sign/SignUp.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt, app/src/main/java/com/umc/yourweather/util/SignUtils.kt, app/src/main/res/layout/activity_sign_up.xml, app/src/main/res/layout/activity_sign_up2.xml
=> [add/#338]회원가입시 안내 문구 

app/src/main/java/com/umc/yourweather/presentation/BottomNavi.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignUp.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt, app/src/main/java/com/umc/yourweather/util/SignUtils.kt, app/src/main/res/layout/activity_sign_up.xml, app/src/main/res/layout/activity_sign_up2.xml
> 광클 시 앱 종료 오류
오류 메시지는 아래와 같았고
> java.lang.IllegalStateException: Fragment MyPageFragment{feb0ee5} (c6275e66-f42b-4b58-a22d-8275a6ad1bbb) not attached to an activity.
gpt 선생님께서 
> "java.lang.IllegalStateException: Fragment not attached to an activity" 오류는 프래그먼트가 액티비티에 연결되지 않은 상태에서 프래그먼트 관련 작업을 수행하려고 할 때 발생합니다. 이 오류는 프래그먼트의 생명주기와 관련이 있으며, 프래그먼트가 액티비티에 연결되어 있는지를 확인하지 않았을 때 발생할 수 있습니다.
이 오류를 해결하기 위해 아래의 사항들을 확인하고 수정하세요:
1. 프래그먼트의 상태 확인: 프래그먼트의 생명주기를 관리할 때, onAttach와 onDetach 메서드에서 프래그먼트가 액티비티에 연결되거나 분리될 때의 작업을 처리해야 합니다. 이를 통해 프래그먼트가 액티비티와 제대로 연결되었는지를 확인할 수 있습니다.
2. 액티비티에서 프래그먼트 관리: 프래그먼트를 액티비티에 추가 또는 제거할 때, 프래그먼트 관련 작업을 수행하는 메서드를 호출하는 곳에서 프래그먼트의 상태를 확인하세요. 예를 들어, onCreate, onCreateView, onResume 등의 메서드에서 프래그먼트 관련 작업을 수행할 때 프래그먼트의 상태가 제대로 연결되어 있는지를 확인하세요.
3. 액티비티에서 프래그먼트를 사용하는 순서: 프래그먼트를 …
=> [fix/#340]광클 시 앱 종료 오류

app/src/main/java/com/umc/yourweather/presentation/BottomNavi.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignUp.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt, app/src/main/java/com/umc/yourweather/util/SignUtils.kt, app/src/main/res/layout/activity_sign_in.xml, app/src/main/res/layout/activity_sign_up.xml, app/src/main/res/layout/activity_sign_up2.xml
=> [remove/#338]구글 로그인 제거

README.md, app/src/main/java/com/umc/yourweather/presentation/BottomNavi.kt, app/src/main/java/com/umc/yourweather/presentation/sign/ResetPw.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignUp.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt, app/src/main/java/com/umc/yourweather/util/SignUtils.kt, app/src/main/res/layout/activity_sign_in.xml, app/src/main/res/layout/activity_sign_up.xml, app/src/main/res/layout/activity_sign_up2.xml
=> [refactor/#336]비번 바꾸기 api 토스트 메시지 수정

app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt, app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt
=> [fix/] home / 기능 오류 수정

app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt
=> [fix/#349] 날씨별 bar 색상 변경

app/src/main/java/com/umc/yourweather/data/remote/response/MemoDailyResponse.kt, app/src/main/java/com/umc/yourweather/data/service/MemoService.kt, app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailviewDiaryAdapter.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView1.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView3.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewEmpty.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify1.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify2.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/HorizontalScrollFragment.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/HorizontalScrollFragment2.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ModifyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ModifyFragment2.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ScrollviewFragment1.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ScrollviewFragment2.kt, app/src/main/res/layout/activity_calendar_detail_view1.xml, app/src/main/res/layout/activity_calendar_detail_view2.xml, app/src/main/res/layout/activity_calendar_detail_view3.xml, app/src/main/res/layout/activity_calendar_detailview_modify1.xml, app/src/main/res/layout/activity_calendar_detailview_modify2.xml, app/src/main/res/layout/alert_dialog_alarm.xml, app/src/main/res/layout/alertdialog_calendar_detailview_modify.xml, app/src/main/res/layout/fragment_horizontal_scroll.xml, app/src/main/res/layout/fragment_horizontal_scroll2.xml, app/src/main/res/layout/fragment_modify.xml, app/src/main/res/layout/fragment_modify2.xml, app/src/main/res/layout/fragment_scrollview1.xml, app/src/main/res/layout/fragment_scrollview2.xml, app/src/main/res/layout/fragment_writing_now.xml
=> [add/#351] 캘린더 상세보기 / 파일 추가

app/src/main/java/com/umc/yourweather/data/remote/response/MemoDailyResponse.kt, app/src/main/java/com/umc/yourweather/data/service/MemoService.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarMonth.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView1.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailView3.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/HorizontalScrollFragment.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/HorizontalScrollFragment2.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ScrollviewFragment1.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/ScrollviewFragment2.kt
=> [fix#/null] Service 잘못된거 수정

app/src/main/java/com/umc/yourweather/presentation/adapter/UnwrittenRVAdapter.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/UnwrittenDetailListFragment.kt
>  미입력 내역 날짜 CalendarDetailviewModify2로 전달
=> [feat/#354] : 미입력 내역 날짜 CalendarDetailviewModify2로 전달

app/src/main/java/com/umc/yourweather/presentation/adapter/WrittenRVAdapter.kt
> 상세 입력 memoId CalendarDetailviewModify1로 전달
=> [feat/#356] : 상세 입력 memoId CalendarDetailviewModify1로 전달

app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw2.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignUp.kt, app/src/main/res/layout/fragment_calendar_total_view.xml
=> [rafactor/#358]자잘한 view 수정

app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt, app/src/main/res/drawable/bg_blue_rec_rain.xml, app/src/main/res/drawable/bg_darkblue_rec_rain.xml, app/src/main/res/drawable/bg_darkblue_rec_thunder.xml, app/src/main/res/drawable/bg_gray_rec_cloud.xml, app/src/main/res/drawable/bg_yellow_rec_sun.xml
=> [fix/#] bar design really 사각형으로 변경

app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailMemoListAdapter.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt, app/src/main/res/drawable/line_calendar_detail_graph.xml, app/src/main/res/layout/activity_calendar_detail.xml, app/src/main/res/layout/item_calendar_detail_memolist.xml
=> [feat] 상세보기 그래프 점찍기

app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt, app/src/main/res/layout/fragment_home_weather_input.xml
=> [fix/#378] home / 강제종료 오류 수정

app/src/main/java/com/umc/yourweather/presentation/share/SaveHomeImgFragment.kt
=> [fix] home / 캡쳐 및 갤러리 저장 기능 수정

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify2.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewTimepicker.kt, app/src/main/res/layout/fragment_calendar_detailview_timepicker.xml
https://github.com/yourweather/yourweather_android/assets/122203161/93e4a66e-22ce-4537-8542-8ef022b9b711
> timepicker뷰 구현
구현
=> [add/#373] : timepicker뷰 구현 

app/src/main/java/com/umc/yourweather/data/remote/response/MemoResponse.kt, app/src/main/java/com/umc/yourweather/data/service/MemoService.kt, app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailMemoListAdapter.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify1.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/TimePickerFragment.kt, app/src/main/res/layout/activity_calendar_detailview_modify1.xml
>  modify1 기능구현 - 특정 메모 반환 API 붙이고 뷰에 전환
=> [feat/#385] modify1 기능구현

app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailMemoListAdapter.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt, app/src/main/res/layout/activity_calendar_detail.xml, app/src/main/res/layout/item_calendar_detail_memolist.xml
=> [remove/#369] 차트 주석처리

app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewModify2.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailviewTimepicker.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/TimePickerCallback.kt
PR 템플릿 작성 TIP)
1) PR을 하기전 ISSUE 생성이 먼저입니다!(해당 이슈번호를 써야하기 때문)
2) PR제목양식
[작업유형/#이슈번호] 뷰이름 / 작업내용
[add/#2] 로그인 / 로그인 뷰 작성완료
3) 개요
작업내용 적어주세요
4) 작업사항 
작업내용안의 작은 포인트들을 체크박스를 이용해 나열해주세요(완료/미완료 항목 구분)
5) 참고사항 및 스크린샷
해당 작업과 관련하여 애매한 부분(팀원들과 논의해야 하는 점)기입 + 스크린샷 또는 영상
6) PR역시 라벨을 꼭 달아주세요 !
----------이 위의 부분은 작성시 삭제하고 아래부터 채우시면 됩니다!-------------
> timepicker기능 구현
=> [feat/ #396] : timepicker/timepicker 기능 구현

app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailMemoListAdapter.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt, app/src/main/res/layout/activity_calendar_detail.xml, app/src/main/res/layout/item_calendar_detail_memolist.xml
> 캘린더 점찍은 버전 
CalendarDetail.kt(calendar 디렉토리에 존재)에선 이런 정보들이 필요합니다 
이쪽으로 이동할때 이 정보들을 인텐트에 넣어서 넘겨주세요
1. weatherId
2. date 
여기서 date는 해당 날짜의 LocalDate를 String타입으로 넣어서 넘겨주시면 됩니다
예시입니다
val mIntent = Intent(context, CalendarDetail: :class. java)
val date = LocalDate.of(2018, 8, 11)  // 2018년 8월 11일
mIntent.putExtra("weatherId", weatherId) 
mIntent.putExtra("date", date.toString()) 
context.startActivity(mIntent)
finsh()
이건 전체 캘린더->캘린더 디테일뷰로 넘어가는 코드입니다
그리고 전 모디파이 2로 이런 정보를 넘겨드리고 있습니다
연/월의 정보를 빼시려면 이렇게 하시면 됩니다(여긴 CalendarDetail.kt)
=> [feat/#369] 캘린더 점찍은 버전 

app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt, app/src/main/res/drawable/bg_gray_ed_fill_5_rect.xml, app/src/main/res/layout/activity_calendar_detail.xml
=> [feat/#369] 수정 완 그래프추가 남음 

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/yourweather/presentation/share/SaveHomeImgFragment.kt, app/src/main/java/com/umc/yourweather/presentation/share/ShareOnInstagramFragment.kt, app/src/main/res/layout/fragment_home_weather_input.xml
>앱 빌드시 2개 생성되는 오류 해결
왜 .. 나머지 커밋이 또 따라왔는지 모르겠네요 .. 일단 올려!
=> [fix/#] 앱 빌드시 2개 생성되는 오류 해결

app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt, app/src/main/res/layout/activity_calendar_weather_detail.xml
> 상세보기에서 메모 삭제 기능 추가
메모 삭제 기능까지 구현했는데, 캘린더로 갔을 때 바로 삭제한 부분이 반영되어 뷰로 보이는 게 아니라 이 부분 수정했으면 좋겠는데 우선 전체 기능 구현을 다 하고 이런 상세한 부분 수정 들어가도록 하겠습니다..! 
https://github.com/yourweather/yourweather_android/assets/83583757/13c2ad5c-ff0d-460f-8496-aed7eb145539
=> [feat/#391] 상세보기에서 메모 삭제 기능 추가

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewStatusbar.kt, app/src/main/res/layout/activity_calendar_detail_view_statusbar.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml
=> [add/#414] : 캘린더 상세보기 상단바 구현 

app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewTimepicker.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/TimePickerFragment.kt, app/src/main/res/layout/activity_calendar_detail.xml
> 타임피커 값을 메모 저장 API의 날짜값으로 보내기
https://github.com/yourweather/yourweather_android/assets/83583757/fb2bba1c-c8a6-43a3-8798-635253e0759e
=> [feat/#416] 타임피커 값을 메모 저장 API의 날짜값으로 보내기

app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarModifyWeatherActivity.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt
> 편집 창 넘어갈 때 해당 메모의 값도 가지고 넘어가서 보여주기
https://github.com/yourweather/yourweather_android/assets/83583757/bd38dd35-6a4a-482f-848b-7525ad0b26f4
=> [fix/#413] 편집 창 넘어갈 때 해당 메모의 값도 가지고 넘어가서 보여주기

app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageNicknameChange.kt
=> [fix/ #421] : 변경된 닉네임으로 SH로 저장

app/src/main/res/drawable/btn_calendardetailview_back.xml, app/src/main/res/layout/activity_calendar_detail.xml, app/src/main/res/layout/activity_calendar_detail_view_statusbar.xml
=> [feat/#423] : 캘린더 상세보기 상단바 추가 

app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt
> finish로 끝나서 기존 화면으로 돌아온 경우 뷰 갱신
https://github.com/yourweather/yourweather_android/assets/83583757/615e3168-c2e8-4b6f-9018-0288b098e634
=> [fix#425] finish로 끝나서 기존 화면으로 돌아온 경우 뷰 갱신

app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDate.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarFragment.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarMonth.kt
=> [fix/#427]calendar total view

app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsMonthlyFragment.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/BarStaticsWeeklyFragment.kt, app/src/main/res/layout/fragment_bar_statics_monthly.xml, app/src/main/res/layout/fragment_bar_statics_weekly.xml
=> [remove/#395] : 말풍선 제거 주석처리

app/src/main/java/com/umc/yourweather/presentation/share/SaveHomeImgFragment.kt, app/src/main/res/layout/fragment_my_page.xml
=> [style/#430] 불필요 기능 주석처리

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageAlarm.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageFragment.kt, app/src/main/res/layout/fragment_my_page.xml
> 토클 버튼 ON 상태 시 알림 울림, 토글 버튼 상태 SH 저장
=> [demo/#404] : 토클 버튼 ON 상태 시 알림 울림, 토글 버튼 상태 SH 저장

app/src/main/AndroidManifest.xml, app/src/main/java/com/umc/yourweather/presentation/weatherinput/InitialNoWeatherFragment.kt, app/src/main/res/layout/fragment_initial_no_weather.xml, app/src/main/res/layout/fragment_my_page.xml
> 닉네임 호출 방법 sh -> 마이페이지 api 로 변경
=> [feat/#434] initial / 닉네임 관련 api 작업

app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageFragment.kt, app/src/main/res/layout/fragment_my_page.xml
=> [hotfix/#436] : 알림 설정 뷰 누락 부분 수정

app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageAlarm.kt
=> [hotfix/#438] : 알림 내용에 유저 닉네임 추가

app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt, app/src/main/res/layout/fragment_icon_statics_monthly.xml, app/src/main/res/layout/fragment_icon_statics_weekly.xml, app/src/main/res/layout/fragment_unwritten_detail_list.xml
=> [fix/#440] 미입력내역, 비교분석 표 잘림 부분 해결

app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDate.kt
PR 템플릿 작성 TIP)
1) PR을 하기전 ISSUE 생성이 먼저입니다!(해당 이슈번호를 써야하기 때문)
2) PR제목양식
[작업유형/#이슈번호] 뷰이름 / 작업내용
[add/#2] 로그인 / 로그인 뷰 작성완료
3) 개요
작업내용 적어주세요
4) 작업사항 
작업내용안의 작은 포인트들을 체크박스를 이용해 나열해주세요(완료/미완료 항목 구분)
5) 참고사항 및 스크린샷
해당 작업과 관련하여 애매한 부분(팀원들과 논의해야 하는 점)기입 + 스크린샷 또는 영상
6) PR역시 라벨을 꼭 달아주세요 !
----------이 위의 부분은 작성시 삭제하고 아래부터 채우시면 됩니다!-------------
> 00
=> [fix] : 기본생성자 추가

app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt, app/src/main/res/layout/fragment_home.xml
=> [fix/#449] home / 광고 뷰 오류 해결 및 너비 수정

app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarModifyWeatherActivity.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarWeatherDetail.kt, app/src/main/res/layout/activity_calendar_modify_weather.xml, app/src/main/res/layout/activity_calendar_plus_weather.xml, app/src/main/res/layout/activity_calendar_weather_detail.xml
> SeekBar에서 감정 상세 온도 알려주는 텍스트 박스
https://github.com/yourweather/yourweather-android/assets/83583757/e01bb568-1ad7-458a-bde8-da678ed345ff
=> [feat/#453] SeekBar에서 감정 상세 온도 알려주는 텍스트 박스

app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarModifyWeatherActivity.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
> 캘린더 기록입력, 수정 부분 입력 취소 시 다이얼로그 창
https://github.com/yourweather/yourweather-android/assets/83583757/726eb662-3119-471e-8797-3db76d8d9a60
=> [feat/#456] : 캘린더 기록입력, 수정 부분 입력 취소 시 다이얼로그 창

app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt, app/src/main/java/com/umc/yourweather/util/AlertDialogTwoBtn.kt, app/src/main/res/layout/alertdialog_twobtn.xml
> alertdialog 서브타이틀 추가
https://github.com/yourweather/yourweather-android/assets/102938120/de5a0d8d-2dc3-464b-927e-518a35c9387e
=> [feat/#450] alertdialog /  서브타이틀 추가

app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarModifyWeatherActivity.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt
>저장한 경우 다이얼로그 안 뜨게, 서브 타이틀 문구 추가
=> [Fix/#394] 저장한 경우 다이얼로그 안 뜨게, 서브 타이틀 문구 추가

app/src/main/java/com/umc/yourweather/presentation/weatherinput/InitialNoWeatherFragment.kt, app/src/main/res/layout/fragment_initial_no_weather.xml
> 이니셜 뷰 닉네임 글자 수 상관없이 가운데 정렬되게 위치 조정
=> [refactor/#465] initial / 닉네임 글자 수 상관없이 가운데 정렬 되게 위치 조정

app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageNicknameChange.kt, app/src/main/res/drawable/bg_share_img.xml, app/src/main/res/layout/fragment_save_home_img.xml
> 닉네임 변경 부분 글자 수 제한(8글자) 기능 추가
=> [fix/#468] mypagenicknamechange / 글자 수 제한 기능 추가

app/src/main/java/com/umc/yourweather/presentation/adapter/CalendarDetailMemoListAdapter.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt, app/src/main/java/com/umc/yourweather/presentation/sign/FindPw.kt, app/src/main/java/com/umc/yourweather/presentation/sign/ResetPw.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignUp2.kt, app/src/main/res/layout/activity_calendar_detail.xml, app/src/main/res/layout/activity_find_pw.xml, app/src/main/res/layout/activity_find_pw_email.xml, app/src/main/res/layout/activity_pw_reset.xml, app/src/main/res/layout/activity_sign_up.xml, app/src/main/res/layout/activity_sign_up2.xml
=> [fix/#467]sign view

app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarDetailViewTimepicker.kt
=> [fix] : 타임피커 띄어쓰기 삭제

app/src/main/java/com/umc/yourweather/di/UserSharedPreferences.kt, app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt, app/src/main/java/com/umc/yourweather/presentation/calendardetailview/CalendarPlusWeather.kt, app/src/main/java/com/umc/yourweather/presentation/sign/Nickname.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt
=> [fix/#462]자동로그인

app/src/main/res/layout/activity_calendar_modify_weather.xml, app/src/main/res/layout/activity_calendar_plus_weather.xml, app/src/main/res/layout/activity_calendar_weather_detail.xml
=> [fix/#475] : 캘린더 상세보기 편집/저장 버튼 18dp

app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDetail.kt, app/src/main/java/com/umc/yourweather/presentation/sign/SignIn.kt, app/src/main/res/drawable/ic_calendardetailview_temp_orange.xml, app/src/main/res/drawable/ic_calendardetailview_temp_orange_2.xml, app/src/main/res/layout/activity_my_info.xml, app/src/main/res/layout/item_calendar_detail_memolist.xml
=> [fix/#477]뷰 수정

app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloud.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentCloudWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRain.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentRainWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSun.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentSunWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunder.kt, app/src/main/java/com/umc/yourweather/presentation/analysis/WrittenDetailListFragmentThunderWeekly.kt, app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageMyInfo.kt
> 닉네임 변경 후 바로 반영되도록 - 마이페이지 Info 뷰
https://github.com/yourweather/yourweather-android/assets/83583757/5d751840-1c03-47dd-a753-ca690ade5af5
=> [fix/#473] : 마이페이지 API를 붙여서 닉네임 변경 시 바뀐 닉네임이 바로 보이도록 수정

app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeFragment.kt, app/src/main/java/com/umc/yourweather/util/AdTextUtils.kt, app/src/main/res/layout/fragment_home.xml
=> [refactor/#482] home / 광고 뷰 랜덤 솔루션 추가

app/src/main/java/com/umc/yourweather/presentation/weatherinput/HomeWeatherInputFragment.kt, app/src/main/res/layout/fragment_home_weather_input.xml
=> [refactor/#486] weatherinput / 수정

app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageNicknameChange.kt
=> [fix] : 닉네임 빈 경우 힌트로 닉네임 변경

app/src/main/res/layout/fragment_home.xml
=> [fix/#489] home / 레이아웃 수정

app/src/main/res/layout/activity_calendar_modify_weather.xml, app/src/main/res/layout/activity_calendar_plus_weather.xml
#개요
> 캘린더 상세보기 창 seekBar 글씨 비율코딩 수정
=> [fix] : 캘린더 상세보기 창 seekBar 글씨 비율코딩 수정

app/src/main/res/drawable/bg_home_toast.xml
=> [hotfix] home / 토스트 백그라운드 이미지 사이즈 조정

app/src/main/res/layout/toast_home.xml, app/src/main/res/layout/toast_initial.xml, build.gradle
> 홈,이니셜 토스트 메시지 백그라운드 이미지 너비 재조정
=> [fix/#500] toast / bg 이미지 너비 재조정

app/src/main/res/layout/activity_calendar_modify_weather.xml, app/src/main/res/layout/activity_calendar_plus_weather.xml, app/src/main/res/layout/activity_calendar_weather_detail.xml
=> [fix] : 캘린더 상세보기 창 아이콘 가운데 정렬

app/src/main/java/com/umc/yourweather/presentation/mypage/MyPageWithdraw2Activity.kt, app/src/main/java/com/umc/yourweather/util/AlertDialogTwoBtnNoneSubtItle.kt, app/src/main/res/layout/activity_my_page_withdraw2.xml, app/src/main/res/layout/alertdialog_twobtn_none_subtitle.xml
=> [fix]회원탈퇴 뷰 수정

app/src/main/AndroidManifest.xml
> menifest 파일 내 없는 파일 관련 코드 삭제
=> [remove] : menifest 파일 내 없는 파일 관련 코드 삭제

app/build.gradle, app/src/main/AndroidManifest.xml
=> [version/#520]  최초 출시 버전 1.0.0 코드 추가, 최초 출시 최종 코드

app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarDate.kt
> CalendarDate.kt 원래 버전으로 돌리기
@JvmOverloads 썼다가 apk추출할 때 오류나서 생성자 다 만든 버전으로 고쳤었는데 
그래도 오류나서 bulid.gradle에 뭐 추가하니까 오류안났습니다
바꾼 후에 오류안나는거 확인했습니다
https://github.com/yourweather/yourweather-android/assets/109809242/6db9dde5-bcfc-457c-93cf-fbba96a3b344
=> [refactor#518] CalendarDate.kt / CalendarDate.kt 원래 버전으로 돌리기

app/src/main/java/com/umc/yourweather/presentation/calendar/CalendarTotalViewFragment.kt, app/src/main/res/drawable/ic_calendar_arrow_left.xml, app/src/main/res/drawable/ic_calendar_arrow_right.xml, app/src/main/res/layout/fragment_calendar_total_view.xml
> 캘린더에서 화살표 위치 픽스
디스코드 프론트방에 인증영상 올리겠습니다!
=> [fix/#522]캘린더에서 화살표 위치 픽스

app/src/main/java/com/umc/yourweather/presentation/sign/SignUpActivity.kt
=> [hotfix/#534] : 다시 백... 이미 가입한 유저 검사 주석처리

app/src/main/java/com/umc/yourweather/presentation/BottomNaviActivity.kt
> 홈화면 비는 현상 해결 
원래 월조회 레트로핏써서 오늘 날짜와 일치하는 기록이 있으면 홈화면, 아니면 이니셜 화면 띄우도록 했는데 지금 메모삭제가 제대로 안되는 오류가 있어서 이런 현상이 일어난 것 같습니다..! 해당 레트로핏 홈화면 조회 api로 교체해서 null 일경우 이니셜 화면으로 변경되도록 수정했습니다. 디코에 영상 올릴게유
=> [fix/#536] : 홈화면 비는 현상 해결 

app/src/main/res/values/strings.xml
=> [fix/#542] : app_name 유어웨더로 변경
